# Generated by Django 5.2.7 on 2025-10-09 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('birthYear', models.IntegerField(blank=True, null=True)),
                ('heightCm', models.FloatField(blank=True, null=True)),
                ('weightKg', models.FloatField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, max_length=20)),
                ('lifestyle', models.CharField(blank=True, max_length=20)),
                ('diet', models.CharField(blank=True, max_length=40)),
                ('allergies', models.JSONField(blank=True, default=dict)),
                ('maxes', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
