# Generated by Django 5.2.7 on 2025-10-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprofile',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='bmr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='tdee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
