# Generated by Django 5.2.7 on 2025-10-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fitnessprofile_bmi_fitnessprofile_bmr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprofile',
            name='proteinIntake',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
