# Generated by Django 5.2.7 on 2025-11-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fooditem_dailylog_pantryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='quantity',
            field=models.FloatField(default=1.0, help_text='In grams'),
        ),
    ]
