# Generated by Django 5.2.7 on 2025-12-07 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pantryitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantryitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='pantryitem',
            name='unit',
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='core.fitnessprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
