# Generated by Django 5.2.7 on 2025-12-08 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pantryitem_quantity_remove_pantryitem_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('avg_daily_calories', models.FloatField(default=0)),
                ('avg_daily_protein', models.FloatField(default=0)),
                ('avg_daily_carbs', models.FloatField(default=0)),
                ('avg_daily_fat', models.FloatField(default=0)),
                ('deficit', models.FloatField(default=0)),
                ('starting_weight', models.FloatField(default=0)),
                ('ending_weight', models.FloatField(default=0)),
                ('weight_change', models.FloatField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summary', to='core.fitnessprofile')),
            ],
        ),
    ]
