# Generated by Django 5.2.7 on 2026-04-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_weeklysummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklysummary',
            options={'ordering': ['-week_start']},
        ),
        migrations.AlterModelOptions(
            name='weightlog',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='isPremium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='weeklysummary',
            unique_together={('profile', 'week_start')},
        ),
    ]
