# Generated by Django 5.2.7 on 2026-04-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_weeklysummary_options_alter_weightlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprofile',
            name='restore_last_used',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='streak_at_break',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='streak_broken_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='streak_last_logged',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='weight_unit_preference',
            field=models.CharField(default='kg', max_length=5),
        ),
    ]
