# Generated by Django 5.2.7 on 2026-04-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_fooditem_portion_size_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='cached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
