# Generated by Django 5.2.7 on 2026-04-22 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fooditem_barcode_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprofile',
            name='tdee_override',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('duration_minutes', models.FloatField()),
                ('calories_burned', models.FloatField()),
                ('met_value', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='core.fitnessprofile')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
